### PR TITLE
Add Olimex Olinuxino A20 LIME2

### PR DESCRIPTION
**Pull request by svheymann**
As discussed here:
[Issue 1026](https://github.com/KiCad/kicad-library/issues/1026)

### CODE REVIEW

**Comment by svheymann** [comment]
In which lib should i put the matching symbols?

**Comment by svheymann** [comment]
I dont like to seem unpatiently, but do i have to change something to get this merged?

**Comment by SchrodingersGat** [comment]
Hi @svheymann thanks for reminding us :)

### RefDes
Please move Second RefDes (on F.Fab layer) to the middle of the symbol (0,0)

### Courtyard
Courtyard needs to be extended around the entire footprint

### Paste Layer
The SMD pads do not have the paste layer enabled. Is this on purpose? This means that this footprint would not be able to be loaded on an SMT PnP machine

Cheers,

**Comment by svheymann** [comment]
done.

**Comment by svheymann** [comment]
Hmm. How can i find out why this check fails? The build log seems empty...

**Comment by SchrodingersGat** [comment]
@svheymann not sure why the build log looks empty - seems fine to me?

Two small things to go and then I think we can merge:

1. Change the **Silkscreen** RefDes text from `**Ref` to `REF**`
1. Add silkscreen boundary. e.g.

2017-03-16 22_41_51-footprint editor no active library

Thanks!

**Comment by svheymann** [comment]
done.

**Comment by SchrodingersGat** [comment]
Ok, great :)

**Pull request merged**
