### PR TITLE
Add Maple Mini Microcontroller module by LeafLabs

### PR DESCRIPTION
**Pull request by Rantanen**
Maple Mini module footprint.

See kicad/kicad-library#1608.

### CODE REVIEW

**Comment by Rantanen** [comment]
I moved the F.Fab module name outside the footprint as that seemed to be the case with most of the footprints I checked. However after seeing the comments in #7, I'll revert that change.

**Comment by jkriege2** [comment]
Having F.Fab mark outside was an initial shot at this ... by now we try and have the F.Fab-REF in the center o f the footprint (i.e. inside), unless this is absolutely imposible.

Best,
JAN

**Comment by Rantanen** [comment]
The F.Fab-REF was always in the center in this footprint as per KLC. What KLC doesn't mention is the recommended place for the F.Fab-Name. Most components have it below the footprint (as it's too long to fit). Looking at the components where it would fit inside, it seems like most still have it below. Although pile of these samples don't really follow KLC anyway.

**Comment by SchrodingersGat** [comment]
@Rantanen this looks great, only questions is why the text on fabrication layer is upside down? If you can fix this I shall merge. Thanks

**Comment by Rantanen** [comment]
Fixed now.

No idea what was going on there. The graphics looked just fine in the footprint editor and even the text rotation was just fine:

image
image

Fixed by changing rotation to 90 degrees and back. 🤷‍♂️

**Comment by SchrodingersGat** [comment]
Thanks! Weird.

**Pull request merged**
