### PR TITLE
added arduino nano footprints

### PR DESCRIPTION
**Pull request by jkriege2**
2017-02-19 17_04_40-footprint editor no active library

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Same here - I don't think the `_WithMountingHoles` is required...

**Comment by SchrodingersGat** [comment]
Great footprints Jan, just a couple of tweaks.

1. Generally speaking the word `with` should never be required for a name. I think `_MountingHoles` is enough.
2. Please rotate the REF** and value on the F.Fab layer so they are consistent across both parts (I like the vertical alignment as per the longer part name)

**Comment by jkriege2** [comment]
Hi!

ahhh ... I didn't post screenshots of all 2 footprints. There is a Version with and without mounting holes!

JAN

**Comment by jkriege2** [comment]
- ad 2) Done!
- ad 1) I would keep the With ... tried it without, but `Arduino_Nano_MountingHoles` somehow sounds like ONLY the mounting holes ...

Best,
JAN

**Pull request merged**
