### PR TITLE
Add ardunio uno

### PR DESCRIPTION
**Pull request by jkriege2**
2017-02-19 17_46_15-footprint editor no active library

2017-02-19 17_46_57-footprint editor no active library

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Unless you plan on adding a version that does not have mounting holes, I don't think the extraneous text `_WithMountingHoles` is needed?

**Comment by SchrodingersGat** [comment]
See comments as per https://github.com/KiCad/Modules.pretty/pull/2 and the word `with` :)

**Comment by SchrodingersGat** [comment]
And I think that `MountedFromLS` might be better stated as `ReverseMount` ?

**Comment by jkriege2** [comment]
Hi!

ahhh ... I didn't post screenshots of all 4 footprints. THere are Version with and without mounting holes of both variants!

JAN

**Comment by SchrodingersGat** [comment]
(`from` is another word that is probably extraneous for a footprint name)

**Comment by SchrodingersGat** [comment]
Yep I just spotted that (and deleted my first comment, sorry :) )

**Comment by jkriege2** [comment]
In https://github.com/KiCad/Potentiometers.pretty we use `_MountLS` ... maybe that's better?

**Comment by SchrodingersGat** [comment]
`_MountLS` is certainly succinct but I am concerned that the LS abbreviation is too opaque? 

LS (lower side) does not match any Kicad nomenclature, and I do not think it is the "accepted" standard - unless you can point me to an example of it being used elsewhere?

In general I get a lot more search results for the term "Reversed" e.g. "reverse mount LED", "reverse mount potentiometer" etc.

Other options may be:
* RearMount
* Reversed
* BackMount
* Underside
* Flipped
* Flip

Any other options? `_MountLS` might not be too bad but perhaps we can come up with something better.

**Comment by jkriege2** [comment]
Hi!

I decided to use `_BackMount` I think that's best, as it countains "Mount" and also reference Back, which is also used in B.SilkS and B.Fab for the BACKside ...

OK with you? If I have time, I can look through some of the existing libs and do some renames ... but that might take some time.

JAN

**Comment by SchrodingersGat** [comment]
Ok I am happy with that.

For this PR can you please change `_WithMountingHoles` to `_MountingHoles`. All looks good apart from that.

**Comment by SchrodingersGat** [comment]
Yep, that is fine with me.

**Pull request merged**
