### PR TITLE
Nucleo 144 footprints

### PR DESCRIPTION
**Pull request by El3ctr0nic**
Initial

### CODE REVIEW

**Comment by El3ctr0nic** [comment]
Check pls :)
I want add next footprints and  components xD

regards,
Marcin

**Comment by SchrodingersGat** [comment]
Hi @El3ctr0nic please remove the word `with` from the names.

e.g. `ST_Morpho_Connector_144_STLink_MountingHoles`

**Comment by El3ctr0nic** [comment]
Hi,
Sorry for late. I was very busy.
Now schould be ok.

Regards,
Marcin

**Comment by SchrodingersGat** [comment]
Thanks!

**Pull request merged**
