### PR TITLE
Footprints for Adafruit HUZZAH ESP8266 breakout.

### PR DESCRIPTION
**Pull request by mignon-p**
[Product page](https://www.adafruit.com/product/2471).

huzzah

huzzah-holes

### CODE REVIEW

**Comment by Misca1234** [comment]
About holes, see comment in 
https://github.com/KiCad/kicad-library/pull/1585

**Comment by Misca1234** [comment]
Btw, Where did you get the physical distances from ?
like the distance form the corner holes to the connections holes, the size of the corner holes and connection holes ?

**Comment by mignon-p** [comment]
> Btw, Where did you get the physical distances from ?
> like the distance form the corner holes to the connections holes,

For the distance from the corner hole to the connection holes, I used [this image](https://cdn-learn.adafruit.com/assets/assets/000/024/680/original/adafruit_products_espinch.png?1429743316) and measured the pixels.  The top of the board is at y position 105, and the center of the upper-left corner hole is at y position 135, and we know from the dimensions in the drawing that this is 0.1 inches, or 100 mils.  Therefore, there are 30 pixels per 100 mils.  The y position of the upper-left connection hole is at y position 180.  Therefore it is 45 pixels below the center of the corner hole, which would make it 150 mils below the center of the corner hole.

> the size of the corner holes

The corner holes are for M2.5 screws, so I just used 2.5 mm as the diameter.   Perhaps I should have added some additional clearance, though?

> and connection holes ?

The breakout board is meant to have male header soldered onto it.  In my application, I want my PCB to have sockets which the breakout board's male headers would plug into.  I'm using [this socket](https://www.digikey.com/product-detail/en/sullins-connector-solutions/PPPC101LFBN-RC/S7043-ND/810182), so that's what I based the hole diameter on.  ([This drawing](https://media.digikey.com/pdf/Catalog%20Drawings/Connectors/PP_CXX1LFBN_FTPRNT.jpg) recommends a hole diameter of 1.02 mm.)

The other way to mount the breakout board would be to insert the male header from the board directly into your PCB.  So let's assume the headers are something [like this](https://www.digikey.com/product-detail/en/sullins-connector-solutions/PRPC010SAAN-RC/S1011EC-10-ND/2775244).  In [its datasheet](https://media.digikey.com/PDF/Data%20Sheets/Sullins%20PDFs/xRxCzzzSxxN-RC_ST_11635-B.pdf), it recommends a hole diameter of 1.0 mm.  So, the 1.02 mm holes should work fine for that use case, too.

**Comment by ghost** [comment]
> The corner holes are for M2.5 screws, so I just used 2.5 mm as the diameter. Perhaps I should have added some additional clearance, though?

Normal clearance for M2.5 screw is 2.9mm.

http://www.amesweb.info/Screws/ClearanceHolesMetricFasteners.aspx

**Comment by mignon-p** [comment]
> Normal clearance for M2.5 screw is 2.9mm.

Thanks; I've increased the hole size to 2.9mm.

holes-29

**Comment by mignon-p** [comment]
Based on [this post](https://forum.kicad.info/t/plated-versus-non-plated-for-mechanical-holes/7635/9), I've changed the type of the mounting holes to "Through-hole" instead of "NPTH, Mechanical".

huzzah-plated

**Comment by jkriege2** [comment]
Nice work!

Thanks,
JAN

**Pull request merged**
