### PR TITLE
Nucleo64

### PR DESCRIPTION
**Pull request by El3ctr0nic**
Footprints for nucleo 64 :)

Pls Merge xD should be ok

### CODE REVIEW

**Comment by El3ctr0nic** [comment]
Hi, Can someone check My PR??

**Comment by El3ctr0nic** [comment]
Hi
,
Why thread is ded??  Something is wrong??

Regards,
Marcin

**Comment by SchrodingersGat** [comment]
Hi @El3ctr0nic just busy is all. Sorry that this PR got forgotten.

Two small adjustments and then good to merge:

1. There is enough room to put the name (on F.Fab layer) inside the footprint
1. Please make pin-1 rectangular.

2017-06-08 18_26_26-footprint editor no active library

**Comment by poeschlr** [comment]
Please add a link to the datasheet to the description field of the footprints.

Is the idea of this footprint to create a board that connects to the nucleo? If so, the lines on fab, silk and courtyard should be moved to the bottom or you need to mirror the footprint. (I would go with the first option.)

Or is the idea to create a clone of the nucleo board? Then the footprint is ok.

Your outline is moved towards the bottom by a bit. (All other measurements seem to be ok.)
screenshot from 2017-06-08 10-32-07

Is there a special reason why you have a courtyard offset of 0.5mm instead of 0.25 like for example the arduino nano footprint?

For future pull request:
Add a link to the datasheet in the description of the pull request.
Add screenshots of your footprint.

**Comment by El3ctr0nic** [comment]
nuc

**Comment by poeschlr** [comment]
You did not answer these questions:
Is the idea of this footprint to create a board that connects to the nucleo? If so, the lines on fab, silk and courtyard should be moved to the bottom or you need to mirror the footprint. (I would go with the first option.)

Or is the idea to create a clone of the nucleo board? Then the footprint is ok.

It might also be a good idea to include some sort of pin 1 marker on the fab and silk layer. Here my suggestions:
screenshot from 2017-06-30 12-04-54

**Comment by poeschlr** [comment]
I also found a minor problem. There is a short line on silk near the outline a bit above pin 1 that looks out of place:
screenshot from 2017-06-30 12-17-36

**Comment by El3ctr0nic** [comment]
I create copy of nucleo board. Shield comes soon

**Comment by poeschlr** [comment]
I think it should then have _clone added to its name. @SchrodingersGat what do you think?

**Comment by El3ctr0nic** [comment]
Ok i made shield footprints too to have full review.
I should add to name _Shield or leave them names as is??

**Comment by poeschlr** [comment]
In preparation for the Kicad v5 release this repo is archived.
Please re submit your contribution over at the new repo https://github.com/KiCad/kicad-footprints
Sorry for the inconvenience this causes.

**Pull request closed without merging**
