### PR TITLE
Add MOD-nRF8001

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by poeschlr** [comment]
I'm kind of confused by the rectangle on the silk layer. What should this represent?
Normally the silk screen should hold the outline of the part in such a way that it is completely outside of the part itself. (visible after assembly)
And the reference on silk should also be outside the part.

The rectangle on the fab layer seems to have the wrong size in y direction.
Shouldn't it be 1300x900mil (33.02x22.86mm)? It currently is 33x27.2mm. I would accept the x direction but the y direction is definitely wrong.

The footprint is missing pin 1 markers on silk and fab layer.

Some information for further reference (intended to help us reviewers):

[Dimensions drawing **sadly not metric**](https://www.olimex.com/Products/Modules/RF/MOD-nRF8001/resources/dimensions_mod-nrf8001.png)
[pinout](https://www.olimex.com/Products/Modules/RF/MOD-nRF8001/resources/MOD-NRF8001-pinout.png)

**Comment by poeschlr** [comment]
Also please fill out the 3d model information.
The path should be ${KISYS3DMOD}/modules.3dshapes/MOD-nRF8001.wrl
Scale should be 1,1,1
offset and rotation 0,0,0

You do not need to provide the model itself. Just fill out the settings such that it can be added later on without changing the footprint.

**Comment by piotr-wiszowaty** [comment]
Corrections pushed.

**Comment by piotr-wiszowaty** [comment]
Correction pushed. check_kicad_mod.py complained that "modules.3dshapes" 
should
be "Modules.3dshapes".

**Comment by poeschlr** [comment]
@SchrodingersGat It seems i am not a member of this repo. (Modules.pretty)

**Comment by poeschlr** [comment]
The footprint looks very nice. But it might fit better in the [RF_Modules repo](https://github.com/KiCad/RF_Modules.pretty). (Other Bluetooth modules are located in there.) If you move the footprint over there, link back to this pull request.

I think the Reference should be on the upper side of the footprint. The value should be outside of the footprint on the bottom.

Also maybe the pin 1 marker would look better as in this:
screenshot from 2017-07-08 23-26-43

**Comment by SchrodingersGat** [comment]
@poeschlr fixed the permissions, thanks.

This footprint should indeed to in RF_Modules

**Comment by piotr-wiszowaty** [comment]
Moved to RF_Modules.

**Pull request closed without merging**
