### PR TITLE
modules: add chip and chip-pro

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Add CHIP and CHIP-PRO footprints following https://github.com/KiCad/kicad-library/pull/654.

The internal silkscreen of CHIP-PRO should be a egde cut because the PCB need to be removed below the module. However, Edge Cuts is not available in the footprint editor.... See following screenshot and following photo of the CHIP-PRO dev kit which illustrate that (CHIP-PRO is black, PCB is white).

capture

cutjumpers

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please address errors as per the Travis checks.

1. Add text "%R" to the F.Fab layer @ (0,0)
1. Add module outline to F.Fab
1. Adjust silkscreen width

**Comment by SchrodingersGat** [comment]
Also you can open the file in a text editor and change the offending lines to "Edge.Cuts" and that will work.

**Comment by SchrodingersGat** [comment]
Another option is to add text to the user comments layer saying "PCB cutout" or similar

**Comment by evanshultz** [comment]
@myfreescalewebpage Will you be able to make the changes mentioned above so this PR can be merged?

**Comment by myfreescalewebpage** [comment]
@evanshultz yes sorry I'm late on many PR at this moment but will do my best to fix them in coming days/weeks. Thanks for your review.

**Comment by myfreescalewebpage** [comment]
Still violating 8.2 because anchor is kept on pin 1 for chip pro module. Datasheet of the manufacturer all reference to pin 1 so I think it's better like that isn't it ?

**Comment by evanshultz** [comment]
@myfreescalewebpage I was just chasing old PRs.

@jkriege2 @SchrodingersGat You guys reviewed this or the referenced PR. Would you be able to do this one?

**Comment by jkriege2** [comment]
Hi!

- we should stick to the KLC here and move the anchor of the SMD-version where the script suggests it (i.e. the center of the device).
- In both symbols the outer silkscreen should be set off a bit from the exact outline on F.Fab, e.g. like here:
2017-02-19 17_04_40-footprint editor no active library
- the extensive inner drawing on MODULE_NEXTTHINGCO_CHIP sholud be moved to the F.Fsab-layer (keep the rectangles surrounding the pinheaders, but the USB Host, A/V jack, USB OTG and BAT should be moved (including their lines).

Best,
JAN

**Comment by myfreescalewebpage** [comment]
@jkriege2 for the first remark, how to to it easily ? All the dimensions are referenced to the pin 1 and the dimension of the module are not standard, review an d possible modifications will just be impossible after moving the anchor (today all dimensions are referenced to pin 1)
For the other remarks, please can you improve KLC and KLC checkers also ? I will try to do the modification of the parts tomorrow.

**Comment by myfreescalewebpage** [comment]
@jkriege2 Modifications of silkscreen done.

However, for the anchor of the CHIPPRO module, I think it is definitively better to keep it on pin 1. And in any case I don't know how to move to the center of the footprint, which is not "attached" to something "real" on the drawing. This need to compute the position of everything on the drawing from the center of the module....

**Comment by SchrodingersGat** [comment]
Hi @myfreescalewebpage lets' see if we can't get this merged.

1. Please rotate 90 degrees CW such that pin-1 is in the top-left
1. Use the anchor tool to align the origin with the center of the part, rather than pin-1

Other than that, looks good to me :)

**Comment by poeschlr** [comment]
In preparation for the Kicad v5 release this repo is archived.
Please re submit your contribution over at the new repo https://github.com/KiCad/kicad-footprints
Sorry for the inconvenience this causes.

**Pull request closed without merging**
